from . import delegation
from . import delegation_line
from . import ir_model_access
from . import ir_rule
from . import ir_ui_menu
from . import ir_ui_view
from . import mail_mail
from . import mail_template
from . import res_groups
from . import res_users
