{
    "name": "OpenEduCat Digital Library",
    "summary": "Digital library for PDF, EPUB and audiobook materials",
    "author": "OpenEduCat Inc",
    "sequence": 10,
    "installable": True,
    "auto_install": False,
    "application": True,
    "website": "https://www.openeducat.org",
    "category": "Education",
    "version": "19.0.1.0",
    "depends": [
        "base",
        "website",
        "portal",
        "openeducat_core_enterprise",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/digital_library_portal_menu.xml",
        "views/digital_library_read_pdf_website.xml",
        "views/digital_library_website_view.xml",
        "views/material_detail_website.xml",
        "views/op_digital_library_category_view.xml",
        "views/op_digital_library_material_view.xml",
        "views/op_digital_library_enrollment_view.xml",
        "views/menu.xml",
    ],
    "demo": [
        "demo/author_demo.xml",
        "demo/material_tag_demo.xml",
        "demo/publisher_demo.xml",
        "demo/material_demo.xml",
        "demo/category_demo.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "openeducat_digital_library/static/src/css/digital_library.scss",
            "openeducat_digital_library/static/src/js/jszip.min.js",
            "openeducat_digital_library/static/src/js/epub.js",
            "openeducat_digital_library/static/src/js/script.js",
            "openeducat_digital_library/static/src/js/my_library.js",
            "openeducat_digital_library/static/src/js/material_detail.js",
        ],
        "web._assets_primary_variables": [
            "openeducat_digital_library/static/src/css/primary_variables.scss",
        ],
    },
    "images": [],
    "license": "Other proprietary",
}
