{
    "name": "OpenEducat Dashboard KPI",
    "summary": "Responsive KPI dashboards for OpenEduCat",
    "author": "OpenEduCat Inc",
    "sequence": 10,
    "installable": True,
    "auto_install": False,
    "website": "https://www.openeducat.org",
    "category": "Tools",
    "version": "19.0.1.0",
    "images": [],
    "depends": [
        "base",
        "web",
        "base_setup",
        "openeducat_admission",
        "openeducat_attendance",
        "openeducat_quiz",
        "openeducat_classroom_enterprise",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/dashboard_pro_security.xml",
        "data/default.xml",
        "views/dashboard_pro_theme_view.xml",
        "views/dashboard_pro_view.xml",
        "views/element_view.xml",
        "menus/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "openeducat_dashboard_kpi/static/src/css/element.css",
            "openeducat_dashboard_kpi/static/src/css/grid_configuration.css",
            "openeducat_dashboard_kpi/static/src/css/dashboard_odoo19.css",
            "openeducat_dashboard_kpi/static/src/js/formatting_function.js",
            "openeducat_dashboard_kpi/static/src/js/date_widget.js",
            "openeducat_dashboard_kpi/static/src/js/dashboard_pro_domain.js",
            "openeducat_dashboard_kpi/static/src/js/components/colorpicker.js",
            "openeducat_dashboard_kpi/static/src/js/components/dashboard_theme.js",
            "openeducat_dashboard_kpi/static/src/js/components/chart_renderer.js",
            "openeducat_dashboard_kpi/static/src/js/components/dashboard_chart.js",
            "openeducat_dashboard_kpi/static/src/js/components/graph.js",
            "openeducat_dashboard_kpi/static/src/js/components/icon.js",
            "openeducat_dashboard_kpi/static/src/js/components/kpi.js",
            "openeducat_dashboard_kpi/static/src/js/components/kpi_target.js",
            "openeducat_dashboard_kpi/static/src/js/components/link.js",
            "openeducat_dashboard_kpi/static/src/js/components/list.js",
            "openeducat_dashboard_kpi/static/src/js/components/text.js",
            "openeducat_dashboard_kpi/static/src/js/components/tile.js",
            "openeducat_dashboard_kpi/static/src/js/components/to_do_list.js",
            "openeducat_dashboard_kpi/static/src/js/components/widget_toggle_kpi.js",
            "openeducat_dashboard_kpi/static/src/js/dashboard_pro.js",
            "openeducat_dashboard_kpi/static/src/xml/element_template.xml",
            "openeducat_dashboard_kpi/static/src/xml/main_dashboard_template.xml",
        ],
    },
    "demo": [
        "demo/demo.xml",
        "demo/element_demo.xml",
    ],
    "license": "Other proprietary",
}
