{
    "name": "OpenEduCat Backend Theme",
    "summary": "Fully migrated OpenEduCat backend theme for Odoo 19",
    "category": "Tools",
    "version": "19.0.1.0",
    "author": "OpenEduCat Inc",
    "website": "https://www.openeducat.org",
    "depends": ["base", "web"],
    "data": [
        "views/sidebar.xml",
        "views/style.xml",
        "views/web.xml",
        "data/theme_config.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "openeducat_backend_theme/static/src/css/login.css",
            "openeducat_backend_theme/static/src/scss/login.scss",
        ],
        "web.assets_backend": [
            "openeducat_backend_theme/static/src/css/odoo19_full_theme.css",
            "openeducat_backend_theme/static/src/js/edu/apps_menu.js",
            "openeducat_backend_theme/static/src/js/edu/control_panel.js",
            "openeducat_backend_theme/static/src/js/edu/control_legacy_panel.js",
            "openeducat_backend_theme/static/src/js/edu/DropdownItem.js",
            "openeducat_backend_theme/static/src/js/edu/field_upgrade.js",
            "openeducat_backend_theme/static/src/js/edu/home_menu.js",
            "openeducat_backend_theme/static/src/js/edu/home_menu_wrapper.js",
            "openeducat_backend_theme/static/src/js/edu/kanban_renderer_mobile.js",
            "openeducat_backend_theme/static/src/js/edu/search_panel.js",
            "openeducat_backend_theme/static/src/js/edu/user_menu.js",
            "openeducat_backend_theme/static/src/js/edu/web_client.js",
            "openeducat_backend_theme/static/src/js/edu/web_responsive.js",
            "openeducat_backend_theme/static/src/js/edu/backend_theme_customizer.js",
            "openeducat_backend_theme/static/src/js/sidebar.js",
            "openeducat_backend_theme/static/src/xml/backend_theme_customizer.xml",
            "openeducat_backend_theme/static/src/xml/menu.xml",
        ],
    },
    "images": [
        "static/description/openeducat_backend_theme_banner.jpg",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False,
}
